export const GET_CUSTOMER_ORDER_REQUEST = "GET_CUSTOMER_ORDER_REQUEST";
export const GET_CUSTOMER_ORDER_SUCCESS = "GET_CUSTOMER_ORDER_SUCCESS";
export const GET_CUSTOMER_ORDER_FAILURE = "GET_CUSTOMER_ORDER_FAILURE";

export const UPDATE_CUSTOMER_ORDER_REQUEST = "UPDATE_CUSTOMER_ORDER_REQUEST";
export const UPDATE_CUSTOMER_ORDER_SUCCESS = "UPDATE_CUSTOMER_ORDER_SUCCESS";
export const UPDATE_CUSTOMER_ORDER_FAILURE = "UPDATE_CUSTOMER_ORDER_FAILURE";
